### ISSUE TITLE
1.20.5 and 1.21 Feature Compatibility Updates

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#1010]
This issue exists to keep track of _feature updates_ still needed to provide _feature compatibility_ with 1.20.6 and 1.21 features, e.g. support for new mobs or blocks.

Libraries:

- Gamemode 4 Base (`base`):
  - [x] Add new blocks to `full_collision` #1039
    - `chiseled_copper`
    - `exposed_chiseled_copper`
    - `weathered_chiseled_copper`
    - `oxidized_chiseled_copper`
    - `waxed_chiseled_copper`
    - `waxed_exposed_chiseled_copper`
    - `waxed_weathered_chiseled_copper`
    - `waxed_oxidized_chiseled_copper`
    - `chiseled_tuff`
    - `copper_bulb`
    - `exposed_copper_bulb`
    - `weathered_copper_bulb`
    - `oxidized_copper_bulb`
    - `waxed_copper_bulb`
    - `waxed_exposed_copper_bulb`
    - `waxed_weathered_copper_bulb`
    - `waxed_oxidized_copper_bulb`
    - `copper_grate`
    - `exposed_copper_grate`
    - `weathered_copper_grate`
    - `oxidized_copper_grate`
    - `waxed_copper_grate`
    - `waxed_exposed_copper_grate`
    - `waxed_weathered_copper_grate`
    - `waxed_oxidized_copper_grate`
    - `crafter`
    - `trial_spawner`
    - `vault`
    - `polished_tuff`
    - `tuff_bricks`
- Auto Crafting:
  - [x] Confirm 1.20.5 & 1.21 vanilla recipes are included
- Balloon Animals:
  - [x] Add `armadillo` to animal pool #1039
  - [x] Add `wolf` variants (otherwise all wolfs are pale wolfs) #1040
- Crossbow Cartridges:
  - [x] Add `wind_charge` as valid projectile item (#1039)
    - ~~Discuss: Fire Charges are a valid projectile, however, those can't be launched by hand~~ 
- Dangerous Dungeons:
  - [ ] Discuss switching to `trial_spawner`
  - [ ] Make use of `bogged` and `breeze`
- Double Doors:
  - [x] Enable for Copper Doors
- Enchantment Extractors: #1018
  - [x] Verify Mace compatibility
- Everstone: #1031
  - [x] Verify Armadillo compatibility
  - [x] Add Bogged aging 
- Forming Press: #1020
  - [x] Add `tuff_bricks` recipe
- Mending Tanks:
  - [x] Verify Mace compatibility
- Metalllurgy: #1021
  - Moneo:
    - [x] Add Mace
  - Gemini:
    - [x] Add Armadillo
  - Hypexperia:
    - [x] Add Mace
  - Ender Bolt
    - [x] Add Mace
- Orb of Ankou: #1054
  - [x] Add Armadillo Soul
  - [x] Add Bogged Soul
  - [x] Add Breeze Soul
- Percurro Shamir: #1021
  - [x] Add Mace
- Potion Liquids:
  - [ ] Add Ominous Liquid
  - [ ] Add Wind Charging Potion
  - [ ] Add Weaving Potion
  - [ ] Add Oozing Potion
  - [ ] Add Infestation Potion
- Relocators: #1017
  - [x] Verify Crafter compatibility
- Tower Structures:
  - [ ] Discuss switching to `trial_spawner`
  - [ ] Make use of `bogged` and `breeze`
- Tunnel Bores: #1023
  - [x] Add `crafter` to `unbreakable`
  - [x] Add `heavy_core` to `not_rail_solid`
- Washing Tanks: #1022
  - [x] Support Wolf Armor washing

**Comment by BluePsychoRanger** [comment]
Can confirm Auto Crafting properly adds the 1.21 recipes to the custom crafter

**Comment by BluePsychoRanger** [comment]
#1018 adds mace enchantments to enchantment extractors

**Comment by BluePsychoRanger** [comment]
#1020 adds the tuff bricks recipe to forming press

**Comment by BluePsychoRanger** [comment]
Can confirm that maces work in mending tanks

**Comment by BluePsychoRanger** [comment]
#1021 Adds metallurgy feature compatibility for 1.21 (mace shamirs and gemini armadillos)

**Comment by BluePsychoRanger** [comment]
#1022 Adds wolf armor washing to washing tanks

**Comment by BluePsychoRanger** [comment]
#1023 Adds tunnel bore feature compatibility for 1.21 (new blocks)

**Comment by BluePsychoRanger** [comment]
#1031 adds armadillo support and bogged<->skeleton conversions

**Comment by BluePsychoRanger** [comment]
Discussed the following points during the dev day:

> Crossbow Cartridges:
> Discuss: Add wind_charge as valid projectile item -- Fire Charges are a valid projectile, however, those can't be launched by hand

Conclusion: Valid suggestion; implemented in upcoming PR (made by Sheepe)

> Dangerous Dungeons: 
> Discuss switching to trial_spawner
> Make use of bogged and breeze

Conclusion: Not necessary, won’t update; aiming to keep the “vibe” of normal dungeons

> Tower Structures: 
> Discuss switching to trial_spawner 
> Make use of bogged and breeze

Conclusion: Not necessary, won’t update; aiming to keep the “vibe” of normal dungeons

**Comment by Sheepe** [comment]
#1039 adds 1.21 full blocks, armadillo to balloon animals and wind charge to crossbow cartridges

**Comment by Bloo-dev** [comment]
With the notes from above, this issue is complete.
